aws s3 stash qa artifacts integration-build-product.yml v2.2

diff --git a/.github/workflows/integration-build-product.yml b/.github/workflows/integration-build-product.yml
--- a/.github/workflows/integration-build-product.yml
+++ b/.github/workflows/integration-build-product.yml
@@ -1874,9 +1874,10 @@ jobs:
         if: ${{ always() &&  inputs.with_simulation_tests }}
         shell: bash
         id: minio_publish
+        continue-on-error: true
         run: |
-          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.22.35.zip" -o "awscliv2.zip"
-          unzip awscliv2.zip
+          curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64-2.22.35.zip" -o "awscliv2.zip"
+          unzip -q awscliv2.zip
           sudo ./aws/install --update
           URI_OBJ_PATH=ci-artifacts/${{ github.repository }}/$(date '+%Y_%m_%d')/${{ github.run_id}}/${{ github.job }}/attempts/${{ github.run_attempt }}
 
@@ -1885,13 +1886,14 @@ jobs:
           MAX_RETRIES=5
           RETRY_DELAY=10
           SUCCESS=false
+
           for i in $(seq 1 $MAX_RETRIES); do
            echo "Attempt $i of $MAX_RETRIES: Uploading artifacts to Minio"
-              aws --endpoint-url "${{ env.MINIO_S3_URL }}" \
-                  s3 cp qa_artifacts/ \
-                  s3://$URI_OBJ_PATH \
-                  --recursive \
-                  --content-type="text/plain" \
+                zip -r qa_artifacts.zip qa_artifacts/
+                aws --endpoint-url "${{ env.MINIO_S3_URL }}" \
+                  s3 cp qa_artifacts.zip \
+                  s3://$URI_OBJ_PATH/qa_artifacts.zip \
+                  --content-type="application/zip" \
                   --checksum-algorithm SHA256
               if [[ $? -eq 0 ]]; then
                   SUCCESS=true
@@ -1916,6 +1918,42 @@ jobs:
           AWS_SECRET_ACCESS_KEY: ${{ secrets.minio_secret_key_id }}
           AWS_DEFAULT_REGION: "us-east-1"
           AWS_DEFAULT_OUTPUT: "none"
+
+      - name: Stash QA artifacts (AWS S3)
+        if: ${{ always() && inputs.with_simulation_tests && steps.minio_publish.outcome != 'success' }}
+        shell: bash
+        id: s3_publish
+        run: |
+          URI_OBJ_PATH=ci-artifacts/${{ github.repository }}/$(date '+%Y_%m_%d')/${{ github.run_id}}/${{ github.job }}/attempts/${{ github.run_attempt }}
+          set +e
+          MAX_RETRIES=5
+          RETRY_DELAY=10
+          SUCCESS=false
+
+          for i in $(seq 1 $MAX_RETRIES); do
+            echo "Attempt $i of $MAX_RETRIES: Uploading artifacts to AWS S3"
+            zip -r qa_artifacts.zip qa_artifacts/
+            aws s3 cp qa_artifacts.zip \
+              s3://ci-artefacts-es/$URI_OBJ_PATH/qa_artifacts.zip \
+              --content-type="application/zip" \
+              --checksum-algorithm SHA256
+            if [[ $? -eq 0 ]]; then
+              SUCCESS=true
+              echo "Upload successful!"
+              break
+            else
+              echo "Upload failed. Retrying in $RETRY_DELAY seconds..."
+              sleep $RETRY_DELAY
+            fi
+          done
+          set -e
+          if [[ "$SUCCESS" == "false" ]]; then
+            echo "Failed to upload to AWS S3 after $MAX_RETRIES attempts. Exiting..."
+            exit 1
+          fi
+
+          PUBLISH_URL="https://ci-artefacts-es.s3.eu-south-2.amazonaws.com/$URI_OBJ_PATH" # Construct S3 URL
+          echo "publish_url=$PUBLISH_URL" >> $GITHUB_OUTPUT
 
       - name: Slack message Artifact info
         uses: archive/github-actions-slack@master
