refactor pipeline and temporarily disable tests

diff --git a/.github/workflows/integration-build-platform.yml b/.github/workflows/integration-build-platform.yml
--- a/.github/workflows/integration-build-platform.yml
+++ b/.github/workflows/integration-build-platform.yml
@@ -215,6 +215,7 @@ jobs:
 
   Validation-UI-Tests:
     needs: [Standalone-Validations]
+    if: ${{ false}}
     runs-on: integration-pipeline
     outputs:
       slack_thread_id: ${{ needs.Standalone-Validations.outputs.slack_thread_id }}
@@ -510,6 +511,7 @@ jobs:
           docker image prune --all -f
 
   Validation-Install-Tests:
+    if: ${{ false}}
     needs: [Standalone-Validations]
     runs-on: integration-pipeline
     steps:
@@ -808,6 +810,7 @@ jobs:
 
   Validation-API-Tests:
     needs: [Standalone-Validations]
+    if: ${{ false}}
     runs-on: integration-pipeline
     steps:
       - name: Cleanup Workspace
@@ -1011,6 +1014,7 @@ jobs:
 
   Validation-Flow-Tests:
     needs: [Standalone-Validations]
+    if: ${{ false}}
     runs-on: integration-pipeline
     steps:
       - name: Cleanup Workspace
@@ -1764,6 +1768,7 @@ jobs:
           docker image prune --all -f
 
   Simulator-Validations:
+    if: ${{ false}}
     needs: [Build-Simulator]
     runs-on: integration-pipeline
     steps:
@@ -2051,10 +2056,10 @@ jobs:
           docker image prune --all -f
 
   Robotic-Stack-Integration:
-    needs: [Standalone-Validations]
+    needs: [Simulator-Validations, Validations-Finish]
     runs-on: simul-${{ inputs.cluster }}-queuer
     outputs:
-      slack_thread_id: ${{ needs.Standalone-Validations.outputs.slack_thread_id }}
+      slack_thread_id: ${{ needs.Validations-Finish.outputs.slack_thread_id }}
     steps:
       - name: Cleanup Workspace
         uses: rtCamp/action-cleanup@master
@@ -2262,6 +2267,20 @@ jobs:
         shell: bash
         run: scp -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no product-manifest.yaml ${{ steps.infra_outputs.outputs.ssh_connect_string }}:${{ env.REMOTE_WORKSPACE_PATH }}/product-manifest.yaml
 
+      - name: Remote - create execution folder
+        shell: bash
+        run: |
+          ssh ${{ steps.infra_outputs.outputs.ssh_connect_string }} -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no '
+            set -e
+            cd ${{ env.REMOTE_WORKSPACE_PATH }}
+
+            EXECUTION_FOLDER="$(pwd)/temp"
+            sudo rm -rf $EXECUTION_FOLDER
+            mkdir  -p $EXECUTION_FOLDER/platform
+            cp product-manifest.yaml $EXECUTION_FOLDER/platform/product-manifest.yaml
+            sudo chmod -R 777 $EXECUTION_FOLDER
+          '
+
       - name: Remote - Fetch product version and merge platform product
         shell: bash
         run: |
@@ -2269,11 +2288,10 @@ jobs:
             set -e
             cd ${{ env.REMOTE_WORKSPACE_PATH }}
 
-            mkdir -p simulator_workspace/platform && cp product-manifest.yaml simulator_workspace/platform/product-manifest.yaml
-
             WORKSPACE=/opt/mov.ai/workspace
+            EXECUTION_FOLDER="$(pwd)/temp"
             docker run -u root \
-              -v "$(pwd)/simulator_workspace":$WORKSPACE \
+              -v "$EXECUTION_FOLDER":$WORKSPACE \
               -i registry.cloud.mov.ai/qa/ci-tools:${{ env.CI_INTEGRATION_CONTAINER_VERSION }} \
               merge_platform_product \
               --product_version_search ${{ inputs.vs_product_version_pattern }} \
@@ -2292,9 +2310,10 @@ jobs:
 
             qa_key=simulator_tests
             WORKSPACE=/opt/mov.ai/workspace
+            EXECUTION_FOLDER="$(pwd)/temp"
 
             docker run -u root \
-              -v "$(pwd)/simulator_workspace":$WORKSPACE \
+              -v "$EXECUTION_FOLDER":$WORKSPACE \
               -i registry.cloud.mov.ai/qa/ci-tools:${{ env.CI_INTEGRATION_CONTAINER_VERSION }} \
               fetch_test_by_manifest \
               --file product-manifest.yaml \
@@ -2303,12 +2322,12 @@ jobs:
               --gh_api_pwd ${{ secrets.auto_commit_pwd }}
 
             # install test dependencies
-            target_dir=$(cat simulator_workspace/target_dir.txt)
+            target_dir=$(cat $EXECUTION_FOLDER/target_dir.txt)
             rm -rf venv
             python3 -m venv venv
             . venv/bin/activate
             python3 -m pip install --upgrade pip
-            pip install -i https://artifacts.cloud.mov.ai/repository/pypi-integration/simple --extra-index-url https://pypi.org/simple -r simulator_workspace/$target_dir/requirements.txt
+            pip install -i https://artifacts.cloud.mov.ai/repository/pypi-integration/simple --extra-index-url https://pypi.org/simple -r $EXECUTION_FOLDER/$target_dir/requirements.txt
             sudo apt install -y --allow-downgrades python3-rosnode python3-rosparam python3-rostopic
             export PYTHONPATH="/usr/lib/python3/dist-packages"
           '
@@ -2327,26 +2346,26 @@ jobs:
 
             cd ${{ env.REMOTE_WORKSPACE_PATH }}
 
-            CONFIG_FILE_NAME="basic-standalone-ignition-noetic.json"
-
-            mkdir -p config_workspace/
-            cp product-manifest.yaml config_workspace/product-manifest.yaml
-            cp -r $CONFIG_FILE_NAME* config_workspace/
+            CONFIG_FILE_NAME="standalone-spawner-solution-simulator-noetic.json"
 
             export PATH="$HOME/.local/bin:$PATH"
             WORKSPACE=/opt/mov.ai/workspace
+            EXECUTION_FOLDER="$(pwd)/temp"
+
             docker run -u root \
-              -v "$(pwd)/config_workspace":$WORKSPACE \
+              -v "$EXECUTION_FOLDER":$WORKSPACE \
               -i registry.cloud.mov.ai/qa/ci-tools:${{ env.CI_INTEGRATION_CONTAINER_VERSION }} \
               get_json_value --file $CONFIG_FILE_NAME.ci \
               --key services_version \
               --output_file movai_service_version
             docker run -u root \
-              -v "$(pwd)/config_workspace":$WORKSPACE \
+              -v "$EXECUTION_FOLDER":$WORKSPACE \
               -i registry.cloud.mov.ai/qa/ci-tools:${{ env.CI_INTEGRATION_CONTAINER_VERSION }} \
               get_json_value --file $CONFIG_FILE_NAME.ci \
               --key quickstart_version \
               --output_file quickstart_version
+
+            cp -r $EXECUTION_FOLDER/* ./ && sudo rm -rf $EXECUTION_FOLDER
 
             export USERSPACE_FOLDER_PATH="/opt/userspace"
             sudo mkdir -p $USERSPACE_FOLDER_PATH/.git;sudo chown 1000:1000 $USERSPACE_FOLDER_PATH/ -Rf
@@ -2360,9 +2379,9 @@ jobs:
             sudo sh -c "echo MOVAI_SERVICE_LOGGER_LEVEL=DEBUG >> /etc/movai/config.env"
             sudo chmod -R +r /etc/movai
 
-            wget https://movai-scripts.s3.amazonaws.com/QuickStart_$(cat config_workspace/quickstart_version).bash
-            chmod +x ./QuickStart_$(cat config_workspace/quickstart_version).bash
-            ./QuickStart_$(cat config_workspace/quickstart_version).bash --apps $(cat config_workspace/movai_service_version) $CONFIG_FILE_NAME
+            wget https://movai-scripts.s3.amazonaws.com/QuickStart_$(cat quickstart_version).bash
+            chmod +x ./QuickStart_$(cat quickstart_version).bash
+            ./QuickStart_$(cat quickstart_version).bash --apps $(cat movai_service_version) $CONFIG_FILE_NAME
             MOVAI_USER="ci"
             MOVAI_PWD="4Iva6UHAQq9DGITj"
             for robot in $(movai-cli robots list); do
@@ -2371,10 +2390,62 @@ jobs:
 
             execution_status=$?
             exit $execution_status
-            rm config_workspace/movai_service_version
+            rm movai_service_version
           '
           echo "movai_user=ci" >> $GITHUB_OUTPUT
           echo "movai_pwd=4Iva6UHAQq9DGITj" >> $GITHUB_OUTPUT
+
+      - name: Remote - Firmware Patch
+        shell: bash
+        run: |
+          ssh ${{ steps.infra_outputs.outputs.ssh_connect_string }} -i ~/.ssh/ci_priv_key.pem -o StrictHostKeyChecking=no '
+            set -e
+
+            EXECUTION_FOLDER="$(pwd)/temp"
+            CONTAINER_ID=$(docker ps --format '{{.Names}}' --filter "name=^spawner-.*")
+
+            mkdir -p firmwares/
+            cp ./*.apt firmwares/
+            docker cp firmwares/ $CONTAINER_ID:/tmp/
+
+            # Install system requirements
+            docker exec -t -u root $CONTAINER_ID bash -c "\
+            set -e
+            ls -la /tmp/firmwares/
+            apt update
+            # Add archive-focal-backup proxy
+            echo \"deb [arch=all,amd64] https://artifacts.cloud.mov.ai/repository/ppa-archive-focal-backup focal-backup main\" >> /etc/apt/sources.list.d/movai-backup.list
+            # Add ppa-ports-focal-backup proxy
+            echo \"deb [arch=all,amd64] https://artifacts.cloud.mov.ai/repository/ppa-ports-focal-backup ports-focal-backup main\" >> /etc/apt/sources.list.d/movai-backup.list
+            # Add ros-proxy and ros-proxy-backup
+            echo \"deb https://artifacts.cloud.mov.ai/repository/ppa-proxy-ros-backup ros-backup main\" >> /etc/apt/sources.list.d/movai-backup.list
+            apt update
+            mobros install \$(cat /tmp/firmwares/sys_req_proj_base.apt) -y
+            rm -rf /etc/apt/sources.list.d/movai-backup.list
+            "
+
+            docker restart $CONTAINER_ID
+
+            # Reinforce the container with the firmware packages as /tmp/ is deleted on restart
+            docker cp firmwares/ $CONTAINER_ID:/tmp/
+
+            # Install firmware packages to transform spawner -> studio and then studio -> Project specific
+            docker exec -t -u root $CONTAINER_ID bash -c "\
+            set -e
+            ls -la /tmp/firmwares/
+
+            apt update
+
+            PKG_LIST=\"\$PKG_LIST \$(cat /tmp/firmwares/firmware_proj_specific.apt | tr \" \" "\n")\"
+
+            PKG_LIST=\"\$PKG_LIST \$(cat /tmp/firmwares/simul_firmware_proj_specific.apt | tr \" \" "\n")\"
+
+            echo \"mobros install \$PKG_LIST -y --fail-on-apt-update\"
+            mobros install \$PKG_LIST -y --fail-on-apt-update
+
+            "
+            docker restart $CONTAINER_ID
+            '
 
       - name: Remote - Integration tests
         id: simulation_tests
@@ -2384,8 +2455,8 @@ jobs:
             set -e
             cd ${{ env.REMOTE_WORKSPACE_PATH }}
 
-            test_dir=$(cat simulator_workspace/test_dir.txt)
-            target_dir=$(cat simulator_workspace/target_dir.txt)
+            test_dir=$(cat test_dir.txt)
+            target_dir=$(cat target_dir.txt)
 
             export DISPLAY="$(w -oush | grep -Eo " :[0-9]+" | uniq | cut -d \  -f 2)"
             echo "Display detected (dinamic) is $DISPLAY"
@@ -2399,16 +2470,7 @@ jobs:
             # run tests
             marker='ci'
 
-            extra_options=""
-            if [ "${{ inputs.duration }}" != "UNDEFINED" ] ; then
-              extra_options="--duration ${{ inputs.duration }}"
-            fi
-            if [[ "$(echo -e "${{ steps.simulator_tests_setup.outputs.version }}\n2.0.0-24" | sort -V | head -n1)" == "2.0.0-24" ]]; then
-              extra_options="$extra_options --out-values test-output.json --ext-metrics"
-            fi
-
-            sudo chmod +777 -R simulator_workspace
-            cd simulator_workspace/${target_dir}
+            cd $target_dir
 
             pytest \
                 ${test_dir} \
@@ -2416,7 +2478,8 @@ jobs:
                 --movai-user ${{ steps.install.outputs.movai_user }} \
                 --movai-pw ${{ steps.install.outputs.movai_pwd }} \
                 --tb=short \
-                $extra_options
+                --out-values test-output.json \
+                --ext-metrics
 
             deactivate
           '
