wrap aws s3 cp command with a retry mechanism for v2.1

diff --git a/.github/workflows/integration-build-product.yml b/.github/workflows/integration-build-product.yml
--- a/.github/workflows/integration-build-product.yml
+++ b/.github/workflows/integration-build-product.yml
@@ -1775,15 +1775,31 @@ jobs:
           unzip awscliv2.zip
           sudo ./aws/install --update
           URI_OBJ_PATH=ci-artifacts/${{ github.repository }}/$(date '+%Y_%m_%d')/${{ github.run_id}}/${{ github.job }}/attempts/${{ github.run_attempt }}
-          aws \
-          --endpoint-url ${{ env.MINIO_S3_URL }} \
-          s3 \
-          cp \
-          qa_artifacts/ \
-          s3://$URI_OBJ_PATH \
-          --recursive \
-          --content-type="text/plain"
-
+          
+          MAX_RETRIES=5
+          RETRY_DELAY=10
+          SUCCESS=false
+          for i in $(seq 1 $MAX_RETRIES); do
+           echo "Attempt $i of $MAX_RETRIES: Uploading artifacts to Minio"
+              aws --endpoint-url "${{ env.MINIO_S3_URL }}" \
+                  s3 cp qa_artifacts/ \
+                  s3://$URI_OBJ_PATH \
+                  --recursive \
+                  --content-type="text/plain"
+              if [[ $? -eq 0 ]]; then
+                  SUCCESS=true
+                  echo "Upload successful!"
+                  break
+              else
+                  echo "Upload failed. Retrying in $RETRY_DELAY seconds..."
+                  sleep $RETRY_DELAY
+              fi
+          done
+          if [[ "$SUCCESS" == "false" ]]; then
+              echo "Failed to upload after $MAX_RETRIES attempts. Exiting..."
+              exit 1
+          fi
+          
           PUBLISH_URL="${{ env.MINIO_PUBLIC_URL }}/browser/$URI_OBJ_PATH"
           echo "publish_url=$PUBLISH_URL" >> $GITHUB_OUTPUT
 
