fix yum uploading to nexus

diff --git a/.github/workflows/service-py-deb-workflow.yml b/.github/workflows/service-py-deb-workflow.yml
--- a/.github/workflows/service-py-deb-workflow.yml
+++ b/.github/workflows/service-py-deb-workflow.yml
@@ -572,32 +572,43 @@ jobs:
         if: ${{ matrix.distro == 'rocky8' }}
         shell: bash
         run: |
-            NEXUS_ENDPOINT="artifacts.cloud.mov.ai"
-            NEXUS_REPO="yum-dev"
-            for file in artifacts/*.rpm
-            do
-              RETURN_CODE=$(curl -u "${{ secrets.nexus_publisher_user }}:${{ secrets.nexus_publisher_password }}" \
-              -H "Content-Type: multipart/form-data" \
-              --data-binary "@$file" \
+          NEXUS_ENDPOINT="artifacts.cloud.mov.ai"
+          NEXUS_REPO="yum-dev"
+
+          cd artifacts
+          for file in $(find -name "*.rpm" -not -name "*src*" -printf '%f\n')
+          do
+            echo "Uploading $file"
+            RETURN_CODE=$(curl -X 'POST' -u "${{ secrets.nexus_publisher_user }}:${{ secrets.nexus_publisher_password }}" \
+              "https://$NEXUS_ENDPOINT/service/rest/v1/components?repository=$NEXUS_REPO" \
+              -H 'accept: application/json' \
+              -H 'Content-Type: multipart/form-data' \
               -w '%{http_code}' \
-              "https://$NEXUS_ENDPOINT/repository/$NEXUS_REPO/")
+              -F 'yum.directory=system' \
+              -F "yum.asset=@$file;type=application/x-rpm" \
+              -F "yum.asset.filename=$file"
+            )
 
-              #retry
-              if [[ ! "$RETURN_CODE" =~ ^(200|201|202)$ ]]; then
-                echo "Failed upload with $RETURN_CODE. Retrying"
+            #retry
+            if [[ ! "$RETURN_CODE" =~ ^(200|201|202|204)$ ]]; then
+              echo "Failed upload $file with $RETURN_CODE. Retrying"
 
-                RETURN_CODE=$(curl -u "${{ secrets.nexus_publisher_user }}:${{ secrets.nexus_publisher_password }}" \
-                  -H "Content-Type: multipart/form-data" \
-                  --data-binary "@$file" \
-                  -w '%{http_code}' \
-                  "https://$NEXUS_ENDPOINT/repository/$NEXUS_REPO/")
-              fi
+              RETURN_CODE=$(curl -X 'POST' -u "${{ secrets.nexus_publisher_user }}:${{ secrets.nexus_publisher_password }}" \
+                "https://$NEXUS_ENDPOINT/service/rest/v1/components?repository=$NEXUS_REPO" \
+                -H 'accept: application/json' \
+                -H 'Content-Type: multipart/form-data' \
+                -w '%{http_code}' \
+                -F 'yum.directory=system' \
+                -F "yum.asset=@$file;type=application/x-rpm" \
+                -F "yum.asset.filename=$file"
+              )
+            fi
 
-              if [[ ! "$RETURN_CODE" =~ ^(200|201|202)$ ]]; then
-                echo "Failed upload with $RETURN_CODE. Exiting"
-                exit 1
-              fi
-            done
+            if [[ ! "$RETURN_CODE" =~ ^(200|201|202|204)$ ]]; then
+              echo "Failed upload $file with $RETURN_CODE. Exiting"
+              exit 1
+            fi
+          done
 
   PublishPyPiToExperimental:
     needs: [Raise, Pack, Package-Test, SonarCloud, Package-Test-Rpm]
@@ -706,27 +717,37 @@ jobs:
             NEXUS_ENDPOINT="artifacts.cloud.mov.ai"
             NEXUS_REPO="yum-integration"
 
-            for file in artifacts/*.rpm
+            cd artifacts
+            for file in $(find -name "*.rpm" -not -name "*src*" -printf '%f\n')
             do
-              RETURN_CODE=$(curl -u "${{ secrets.nexus_publisher_user }}:${{ secrets.nexus_publisher_password }}" \
-              -H "Content-Type: multipart/form-data" \
-              --data-binary "@$file" \
-              -w '%{http_code}' \
-              "https://$NEXUS_ENDPOINT/repository/$NEXUS_REPO/")
+              echo "Uploading $file"
+              RETURN_CODE=$(curl -X 'POST' -u "${{ secrets.nexus_publisher_user }}:${{ secrets.nexus_publisher_password }}" \
+                "https://$NEXUS_ENDPOINT/service/rest/v1/components?repository=$NEXUS_REPO" \
+                -H 'accept: application/json' \
+                -H 'Content-Type: multipart/form-data' \
+                -w '%{http_code}' \
+                -F 'yum.directory=system' \
+                -F "yum.asset=@$file;type=application/x-rpm" \
+                -F "yum.asset.filename=$file"
+              )
 
               #retry
-              if [[ ! "$RETURN_CODE" =~ ^(200|201|202)$ ]]; then
-                echo "Failed upload with $RETURN_CODE. Retrying"
+              if [[ ! "$RETURN_CODE" =~ ^(200|201|202|204)$ ]]; then
+                echo "Failed upload $file with $RETURN_CODE. Retrying"
 
-                RETURN_CODE=$(curl -u "${{ secrets.nexus_publisher_user }}:${{ secrets.nexus_publisher_password }}" \
-                  -H "Content-Type: multipart/form-data" \
-                  --data-binary "@$file" \
+                RETURN_CODE=$(curl -X 'POST' -u "${{ secrets.nexus_publisher_user }}:${{ secrets.nexus_publisher_password }}" \
+                  "https://$NEXUS_ENDPOINT/service/rest/v1/components?repository=$NEXUS_REPO" \
+                  -H 'accept: application/json' \
+                  -H 'Content-Type: multipart/form-data' \
                   -w '%{http_code}' \
-                  "https://$NEXUS_ENDPOINT/repository/$NEXUS_REPO/")
+                  -F 'yum.directory=system' \
+                  -F "yum.asset=@$file;type=application/x-rpm" \
+                  -F "yum.asset.filename=$file"
+                )
               fi
 
-              if [[ ! "$RETURN_CODE" =~ ^(200|201|202)$ ]]; then
-                echo "Failed upload with $RETURN_CODE. Exiting"
+              if [[ ! "$RETURN_CODE" =~ ^(200|201|202|204)$ ]]; then
+                echo "Failed upload $file with $RETURN_CODE. Exiting"
                 exit 1
               fi
             done
